# typed: false
# frozen_string_literal: true

# Homebrew formula for PackGuard.
#
# Auto-generated by the release workflow on each `v*` tag.
# Upstream source and template:
#   https://github.com/Tmauc/packguard/blob/main/packaging/homebrew/packguard.rb
# Bug reports for the formula itself:
#   https://github.com/Tmauc/homebrew-packguard/issues

class Packguard < Formula
  desc "Dependency supply-chain scanner: OSV/GHSA + malware/typosquat + policy-driven CI gate"
  homepage "https://github.com/Tmauc/packguard"
  version "0.6.5"
  license "MIT OR Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "4f4cbd55a318137ead2882af141d60bcacf6d22a58c91025c800220ef3578a47"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "b636d710fe22b8bc4ea628508a21ed4df279ded9580c0cd1278efc59d908b3c4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1d42967e848f3fa2e6f2c0e164c33afbe569ec4e65710334a1646ff22b0070e7"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7da6a78f5879db5bddc35a6733d5626ec1233b8991a7bd7a373b5b0aeefaae44"
    end
  end

  def install
    bin.install "packguard"
    # Carry the README + license into Cellar so `brew info packguard`
    # renders the homepage correctly and license audits see a licence
    # file alongside the binary.
    doc.install "README.md" if File.exist?("README.md")
    %w[LICENSE LICENSE-APACHE LICENSE-MIT].each do |f|
      pkgshare.install f if File.exist?(f)
    end
  end

  test do
    # Smoke tests: `--version` prints the tagged version, `init` writes
    # a conservative policy in the temp Testpath sandbox. These two
    # together exercise the binary's IO + its policy crate.
    assert_match version.to_s, shell_output("#{bin}/packguard --version")
    system "#{bin}/packguard", "init", testpath.to_s, "--force"
    assert_predicate testpath/".packguard.yml", :exist?
  end
end
