# typed: false
# frozen_string_literal: true

# Homebrew formula for PackGuard.
#
# Auto-generated by the release workflow on each `v*` tag.
# Upstream source and template:
#   https://github.com/Tmauc/packguard/blob/main/packaging/homebrew/packguard.rb
# Bug reports for the formula itself:
#   https://github.com/Tmauc/homebrew-packguard/issues

class Packguard < Formula
  desc "Dependency supply-chain scanner: OSV/GHSA + malware/typosquat + policy-driven CI gate"
  homepage "https://github.com/Tmauc/packguard"
  version "0.2.0"
  license "MIT OR Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "9611214ee59b55e893b3e00b8c27651f0f40afe0ab41b33a31896d32c5aa49da"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "6410d4af78b3b2f1aaf079faf3478cf6178671c2e7b261bdd735d551f4530e7a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d400df3e83e316d5eed98f87ca4ae796874496debcc326a509a5871e585c07e9"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2be5d3f3c7c121714da6b9dfc258694b8199df30db542f9ef3f2125c2c26d0ef"
    end
  end

  def install
    bin.install "packguard"
    # Carry the README + license into Cellar so `brew info packguard`
    # renders the homepage correctly and license audits see a licence
    # file alongside the binary.
    doc.install "README.md" if File.exist?("README.md")
    %w[LICENSE LICENSE-APACHE LICENSE-MIT].each do |f|
      pkgshare.install f if File.exist?(f)
    end
  end

  test do
    # Smoke tests: `--version` prints the tagged version, `init` writes
    # a conservative policy in the temp Testpath sandbox. These two
    # together exercise the binary's IO + its policy crate.
    assert_match version.to_s, shell_output("#{bin}/packguard --version")
    system "#{bin}/packguard", "init", testpath.to_s, "--force"
    assert_predicate testpath/".packguard.yml", :exist?
  end
end
