# typed: false
# frozen_string_literal: true

# Homebrew formula for PackGuard.
#
# Auto-generated by the release workflow on each `v*` tag.
# Upstream source and template:
#   https://github.com/Tmauc/packguard/blob/main/packaging/homebrew/packguard.rb
# Bug reports for the formula itself:
#   https://github.com/Tmauc/homebrew-packguard/issues

class Packguard < Formula
  desc "Dependency supply-chain scanner: OSV/GHSA + malware/typosquat + policy-driven CI gate"
  homepage "https://github.com/Tmauc/packguard"
  version "0.6.1"
  license "MIT OR Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "c9088e639107f4b5eff7d9bb3d7a87429317088e33eafe3b302273e5fffd6458"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "7566c051c490888a2620d29c12bcad5a719388cc0fc0d14ef9886fadcf7a4eab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "5efa784212e5fec44f197304861f1c22cfca6ab3ec58d670ab2017aa2ba0d87a"
    end
    on_intel do
      url "https://github.com/Tmauc/packguard/releases/download/v#{version}/packguard-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "995f56729347f1851c4c197abb66f811325b93a4fe8cc7418495ca9cb60c8378"
    end
  end

  def install
    bin.install "packguard"
    # Carry the README + license into Cellar so `brew info packguard`
    # renders the homepage correctly and license audits see a licence
    # file alongside the binary.
    doc.install "README.md" if File.exist?("README.md")
    %w[LICENSE LICENSE-APACHE LICENSE-MIT].each do |f|
      pkgshare.install f if File.exist?(f)
    end
  end

  test do
    # Smoke tests: `--version` prints the tagged version, `init` writes
    # a conservative policy in the temp Testpath sandbox. These two
    # together exercise the binary's IO + its policy crate.
    assert_match version.to_s, shell_output("#{bin}/packguard --version")
    system "#{bin}/packguard", "init", testpath.to_s, "--force"
    assert_predicate testpath/".packguard.yml", :exist?
  end
end
